const D=window.RADAR,app=document.querySelector("#app"),TODAY=new Date();
// Estado editorial pessoal — Supabase
const SUPABASE_URL="https://uzqwhdtvoysxweuyvnup.supabase.co",SUPABASE_KEY="sb_publishable_z64gznAmfuqD9zByxE35AQ_kqqKsg9f";
let SB=null,EDITORIAL={user:null,states:new Map(),ready:false};
const stateKey=(type,id)=>type+":"+id;
const stateLabels={
 opportunity:{vou_fazer:"Vou fazer",em_andamento:"Em andamento",sem_interesse:"Não agora",pausado:"Pausado",concluido:"Concluído"},
 story:{avaliar:"Pré-apuração",vou_fazer:"Em andamento",submetida:"Submetida",aceita:"Aceita",em_andamento:"Em produção",pausado:"Pausada",concluido:"Publicada",sem_interesse:"Arquivada"},
 dataset:{vou_fazer:"Salva",em_andamento:"Em uso",concluido:"Já usei",sem_interesse:"Oculta"}
};
function editorialState(type,id){return EDITORIAL.states.get(stateKey(type,id))||null}
function labelState(type,state){let submission={submetida:"Submetida",aceita:"Aceita",rejeitada:"Rejeitada"};return type==="submission"?(submission[state]||state):stateLabels[type]?.[state]||state?.replaceAll("_"," ")||""}
function stateMark(type,id){let x=editorialState(type,id);return x?'<span class="estate '+type+'-state '+x.state+'"><i></i>'+labelState(type,x.state)+'</span>':""}
function stateOptions(type,current){let labels=stateLabels[type]||stateLabels.opportunity;return '<option value="">'+(type==="opportunity"?"Para decidir":type==="story"?"Sem etapa pessoal":"Não salva")+'</option>'+Object.entries(labels).map(([k,l])=>'<option value="'+k+'" '+(current===k?"selected":"")+'>'+l+'</option>').join("")}
function stateControl(type,id){let x=editorialState(type,id),v=x?.state||"";if(!EDITORIAL.user)return'<div class="estatebox"><b>Estado pessoal</b><span class="meta">Entre no Radar para sincronizar decisões e notas.</span><button class="btn" onclick="loginRadar()">Entrar por e-mail</button></div>';return'<div class="estatebox"><b>Estado pessoal</b><select onchange="saveEditorialState(\''+type+'\',\''+id+'\',this.value)">'+stateOptions(type,v)+'</select><textarea id="estate-note" placeholder="Nota pessoal (opcional)">'+(x?.note||"")+'</textarea><button class="btn" onclick="saveEditorialState(\''+type+'\',\''+id+'\',document.querySelector(\'.estatebox select\').value,document.querySelector(\'#estate-note\').value)">Salvar nota</button><span id="estate-save" class="meta"></span></div>'}
function quickState(type,id,state,event){if(event){event.preventDefault();event.stopPropagation()}return saveEditorialState(type,id,state)}
function quickActions(o){if(!EDITORIAL.user)return"";let st=editorialState("opportunity",o.id)?.state;return'<div class="quickactions" onclick="event.stopPropagation()">'+(st!=="vou_fazer"?'<button onclick="quickState(\'opportunity\',\''+o.id+'\',\'vou_fazer\',event)">Vou fazer</button>':"")+(st!=="sem_interesse"?'<button onclick="quickState(\'opportunity\',\''+o.id+'\',\'sem_interesse\',event)">Não agora</button>':"")+'</div>'}
function storySubmissions(id){return[...EDITORIAL.states.values()].filter(x=>x.record_type==="submission"&&submissionData(x)?.storyId===id).sort((a,b)=>(submissionData(b)?.date||"").localeCompare(submissionData(a)?.date||""))}
function submissionData(x){try{return JSON.parse(x?.note||"{}")}catch{return{}}}
function submissionHistory(id){let rows=storySubmissions(id);return '<div class="submissionbox"><h3>Submissões</h3><p class="meta">O histórico permanece salvo mesmo se a pauta voltar para “Em andamento”.</p>'+(EDITORIAL.user?'<div class="submissionform"><input id="submission-destination" placeholder="Veículo, edital, grant ou programa"><input id="submission-date" type="date" value="'+new Date().toISOString().slice(0,10)+'"><button class="btn" onclick="addSubmission(\''+id+'\')">Registrar submissão</button></div>':'')+(rows.length?'<div class="submissionhistory">'+rows.map(x=>{let d=submissionData(x);return'<div class="submissionrow"><div><b>'+d.destination+'</b><div class="meta">'+fmt(d.date)+' · '+labelState("submission",x.state)+'</div></div><div>'+(x.state==="submetida"?'<button class="btn" onclick="resolveSubmission(\''+x.record_id+'\',\'aceita\')">Aceita</button><button class="btn" onclick="resolveSubmission(\''+x.record_id+'\',\'rejeitada\')">Rejeitada</button>':"")+'</div></div>'}).join("")+'</div>':'<p class="meta">Nenhuma submissão registrada.</p>')+'</div>'}
async function addSubmission(storyId){if(!SB||!EDITORIAL.user)return loginRadar();let dest=document.querySelector("#submission-destination")?.value.trim(),date=document.querySelector("#submission-date")?.value;if(!dest)return alert("Informe para onde a pauta foi submetida.");let id=storyId+"--"+Date.now(),payload={user_id:EDITORIAL.user.id,record_id:id,record_type:"submission",state:"submetida",note:JSON.stringify({storyId,destination:dest,date:date||new Date().toISOString().slice(0,10)})};setSync("saving");let {data,error}=await SB.from("editorial_state").upsert(payload,{onConflict:"user_id,record_type,record_id"}).select().single();if(error){setSync("error");return alert("Não foi possível registrar a submissão: "+error.message)}EDITORIAL.states.set(stateKey("submission",id),data);await saveEditorialState("story",storyId,"submetida");}
async function resolveSubmission(id,result){let x=editorialState("submission",id);if(!x||!SB||!EDITORIAL.user)return;let d=submissionData(x);d.resultDate=new Date().toISOString().slice(0,10);setSync("saving");let payload={user_id:EDITORIAL.user.id,record_id:id,record_type:"submission",state:result,note:JSON.stringify(d)},{data,error}=await SB.from("editorial_state").upsert(payload,{onConflict:"user_id,record_type,record_id"}).select().single();if(error){setSync("error");return alert("Não foi possível atualizar a submissão: "+error.message)}EDITORIAL.states.set(stateKey("submission",id),data);await saveEditorialState("story",d.storyId,result==="aceita"?"aceita":"vou_fazer");}
async function loginRadar(){if(!SB)return alert("Sincronização ainda carregando.");let email=prompt("E-mail para receber o link de acesso ao Radar:");if(!email)return;let {error}=await SB.auth.signInWithOtp({email,options:{emailRedirectTo:"https://r4chelxx.github.io/radar-plot-grants-fellowships/"}});alert(error?"Não foi possível enviar o link: "+error.message:"Link de acesso enviado. Abra o e-mail neste dispositivo.")}
async function logoutRadar(){if(SB)await SB.auth.signOut();EDITORIAL.user=null;EDITORIAL.states.clear();EDITORIAL.ready=false;render();renderAuth()}
async function loadEditorial(){if(!SB||!EDITORIAL.user)return;setSync("loading");let {data,error}=await SB.from("editorial_state").select("record_id,record_type,state,note,updated_at");if(error){console.error("Radar state",error);setSync("error");return}EDITORIAL.states=new Map((data||[]).map(x=>[stateKey(x.record_type,x.record_id),x]));EDITORIAL.ready=true;setSync("ok");render()}
async function saveEditorialState(type,id,state,note){if(!SB||!EDITORIAL.user)return loginRadar();setSync("saving");let current=editorialState(type,id);if(!state){let {error}=await SB.from("editorial_state").delete().eq("user_id",EDITORIAL.user.id).eq("record_type",type).eq("record_id",id);if(error){setSync("error");return alert("Não foi possível salvar: "+error.message)}EDITORIAL.states.delete(stateKey(type,id));setSync("ok");render();return}let payload={user_id:EDITORIAL.user.id,record_id:id,record_type:type,state,note:note!==undefined?note:(current?.note||null)};let {data,error}=await SB.from("editorial_state").upsert(payload,{onConflict:"user_id,record_type,record_id"}).select().single();if(error){setSync("error");return alert("Não foi possível salvar: "+error.message)}EDITORIAL.states.set(stateKey(type,id),data);setSync("ok");render();let msg=document.querySelector("#estate-save");if(msg){msg.textContent="Salvo ✓";setTimeout(()=>{if(msg)msg.textContent=""},1600)}}
function setSync(status){EDITORIAL.sync=status;renderAuth()}
function renderAuth(){let el=document.querySelector("#auth");if(!el)return;if(!EDITORIAL.user){el.innerHTML='<button onclick="loginRadar()">Entrar</button>';return}let s=EDITORIAL.sync==="saving"||EDITORIAL.sync==="loading"?"Salvando…":EDITORIAL.sync==="error"?"Não sincronizado":"Sincronizado";el.innerHTML='<span class="syncdot '+(EDITORIAL.sync==="error"?"syncerror":EDITORIAL.sync==="saving"||EDITORIAL.sync==="loading"?"syncbusy":"")+'"></span><span>'+s+'</span><button onclick="logoutRadar()">Sair</button>'}
async function initEditorial(){if(!window.supabase){renderAuth();return}SB=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);let {data:{session}}=await SB.auth.getSession();EDITORIAL.user=session?.user||null;renderAuth();if(EDITORIAL.user)await loadEditorial();SB.auth.onAuthStateChange(async(_,session)=>{EDITORIAL.user=session?.user||null;renderAuth();if(EDITORIAL.user)await loadEditorial();else{EDITORIAL.states.clear();EDITORIAL.ready=false;render()}})}

const fmt=d=>d?new Intl.DateTimeFormat("pt-BR").format(new Date(d+"T12:00:00")):"—",opp=id=>D.opportunities.find(x=>x.id===id),story=id=>D.stories.find(x=>x.id===id),route=()=>location.hash.slice(1)||"visao";
const days=(a,b=TODAY)=>Math.round((new Date(a+"T12:00:00")-b)/864e5),age=o=>o.verified?Math.max(0,-days(o.verified)):null;
function action(o){if(["encerrada","descartada"].includes(o.status)||o.eligibility==="inelegível")return"nenhuma ação";if(o.eligibility==="parcial")return"buscar parceria";if(o.eligibility==="verificar")return"pendente de confirmação";if(o.status==="preparar")return"preparar";if(o.status==="monitorar")return"monitorar";if(o.deadlineStatus?.includes("futura")||o.deadlineStatus?.includes("abre_"))return"aguardar abertura";return"avaliar/aplicar"}
function readiness(o){if(o.eligibility==="inelegível"||["encerrada","descartada"].includes(o.status))return"fora do pipeline";if(o.eligibility==="verificar"||o.eligibility==="parcial")return"baixa";if(o.status==="preparar")return"média";if(o.status==="aberta"&&o.fit>=9)return"alta";return"média"}
function nextStep(o){if(o.eligibility==="inelegível")return"Sem ação: inelegível.";if(["encerrada","descartada"].includes(o.status))return"Monitorar apenas nova edição, se pertinente.";if(o.eligibility==="parcial")return"Identificar parceria que satisfaça as regras antes de adaptar qualquer pauta.";if(o.eligibility==="verificar")return"Há requisito de elegibilidade ainda não confirmado na fonte oficial.";if(o.opens&&days(o.opens)>0)return"Preparar materiais antes da abertura em "+fmt(o.opens)+".";if(o.deadline&&days(o.deadline)>=0&&days(o.deadline)<=14)return"Decidir candidatura e fechar documentos antes de "+fmt(o.deadline)+".";if(o.documents?.length)return"Revisar e preparar: "+o.documents.join(", ")+".";if(o.deadlineStatus==="rolling")return"Avaliar encaixe de uma pauta madura; não adaptar artificialmente.";return"Rever fonte oficial e decidir se entra no pipeline."}
function badge(x,link=true){let v=String(x||"").replaceAll("_"," "),attr=' class="badge" data-theme="'+v.toLowerCase()+'"';return link?'<a'+attr+' href="#tema/'+encodeURIComponent(v)+'" onclick="event.stopPropagation()">'+v+'</a>':'<span'+attr+'>'+v+'</span>'}
function nav(){document.querySelectorAll("nav a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+route().split("/")[0]))}
function head(k,t,l){return'<div class="eyebrow">'+k+'</div><h1>'+t+'</h1><p class="lede">'+l+'</p>'}
function freshness(o){let a=age(o);return a==null?"não verificado":a===0?"verificado hoje":a===1?"verificado há 1 dia":"verificado há "+a+" dias"}
function shortDesc(o){let s=(o.summary||o.desc||"").trim();if(!s)return"";let first=s.split(/(?<=[.!?])\s+/)[0];return first.length>150?first.slice(0,147).trim()+"…":first}
function orow(o){return'<div class="row clickable" onclick="location.hash=\'oportunidade/'+o.id+'\'"><div><div class="org">'+o.org+'</div><h3>'+o.title+' '+stateMark("opportunity",o.id)+'</h3><p class="oppsummary">'+shortDesc(o)+'</p>'+o.themes.map(x=>badge(x)).join("")+quickActions(o)+'</div><div><div class="meta">'+(o.deadline?fmt(o.deadline):o.deadlineStatus==="rolling"?"Fluxo contínuo":"Sem data confirmada")+'</div></div><div><span class="score">'+o.fit+'</span><span class="meta"> / 10</span></div><div>'+badge(o.eligibility,false)+'</div></div>'}
function home(){let active=D.opportunities.filter(o=>!["encerrada","descartada"].includes(o.status)&&o.eligibility!=="inelegível"&&editorialState("opportunity",o.id)?.state!=="sem_interesse"),undecided=active.filter(o=>!editorialState("opportunity",o.id)),selected=active.filter(o=>editorialState("opportunity",o.id)?.state==="vou_fazer"),working=active.filter(o=>editorialState("opportunity",o.id)?.state==="em_andamento"),personal=[...selected,...working],soon=active.filter(o=>o.deadline&&days(o.deadline)>=0&&days(o.deadline)<=30),news=(D.changelog||[]).filter(x=>x.type==="nova-oportunidade"&&days(x.date)>=-7).sort((a,b)=>b.date.localeCompare(a.date)),activeStories=D.stories.filter(s=>["vou_fazer","em_andamento","submetida","aceita"].includes(editorialState("story",s.id)?.state));return head("Inteligência editorial","Radar PLOT<span class='accent'>.</span>","O que merece atenção agora: decisões, trabalho ativo e prazos do PLOT.")+'<div class="metrics"><a class="metric metriclink" href="#oportunidades/decidir"><b>'+undecided.length+'</b><span>para decidir</span></a><a class="metric metriclink" href="#oportunidades/preparar"><b>'+selected.length+'</b><span>em preparação</span></a><a class="metric metriclink" href="#oportunidades/andamento"><b>'+working.length+'</b><span>em andamento</span></a><a class="metric metriclink" href="#oportunidades/prazo30"><b>'+soon.length+'</b><span>prazos em 30 dias</span></a></div>'+(working.length||activeStories.length?'<h2>Em andamento</h2><div class="workgrid">'+working.map(o=>'<a class="workitem" href="#oportunidade/'+o.id+'"><div class="eyebrow">Candidatura</div><h3>'+o.title+'</h3>'+stateMark("opportunity",o.id)+'</a>').join("")+activeStories.map(s=>'<a class="workitem" href="#pauta/'+s.id+'"><div class="eyebrow">Pauta</div><h3>'+s.title+'</h3>'+stateMark("story",s.id)+'</a>').join("")+'</div>':"")+(news.length?'<h2>Novas oportunidades</h2><div class="timeline">'+news.slice(0,6).map(x=>{let o=D.opportunities.find(o=>o.title===x.title);return'<div class="event"><b>'+fmt(x.date)+'</b> · '+(o?'<a href="#oportunidade/'+o.id+'">'+x.title+'</a>':x.title)+'<div class="meta">'+x.detail+'</div>'+(o?quickActions(o):"")+'</div>'}).join("")+'</div>':"")+'<h2>Para decidir</h2>'+(undecided.length?'<div class="list">'+undecided.sort((a,b)=>(a.deadline||"9999").localeCompare(b.deadline||"9999")).slice(0,8).map(orow).join("")+'</div>':'<div class="warning ok"><b>Triagem em dia:</b> nenhuma oportunidade ativa aguarda sua decisão.</div>')+'<h2>Meus próximos prazos</h2>'+(personal.filter(o=>o.deadline&&days(o.deadline)>=0).length?'<div class="timeline">'+personal.filter(o=>o.deadline&&days(o.deadline)>=0).sort((a,b)=>a.deadline.localeCompare(b.deadline)).slice(0,10).map(o=>'<div class="event"><b>'+fmt(o.deadline)+'</b> · <a href="#oportunidade/'+o.id+'">'+o.title+'</a> '+stateMark("opportunity",o.id)+'<div class="meta">'+o.org+'</div></div>').join("")+'</div>':'<p class="meta">Nenhum prazo pessoal selecionado.</p>')}
function download(name,type,content){let b=new Blob([content],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
function exportJSON(){download("radar-plot-oportunidades.json","application/json",JSON.stringify(D.opportunities,null,2))}
function exportCSV(){let cols=["title","org","type","scope","deadline","eligibility","fit","status","verified"],esc=v=>'"'+String(v??"").replaceAll('"','""')+'"';download("radar-plot-oportunidades.csv","text/csv;charset=utf-8","\ufeff"+cols.join(",")+"\n"+D.opportunities.map(o=>cols.map(k=>esc(o[k])).join(",")).join("\n"))}
function exportICS(){let ev=D.opportunities.filter(o=>o.deadline&&!["encerrada","descartada"].includes(o.status)).map(o=>"BEGIN:VEVENT\nDTSTART;VALUE=DATE:"+o.deadline.replaceAll("-","")+"\nSUMMARY:"+o.title.replaceAll(",","\\,")+" — Radar PLOT.\nDESCRIPTION:"+o.org.replaceAll(",","\\,")+"\nURL:"+o.rules+"\nEND:VEVENT").join("\n");download("radar-plot-prazos.ics","text/calendar","BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//PLOT//Radar//PT-BR\n"+ev+"\nEND:VCALENDAR")}
function opportunities(){let themes=[...new Set(D.opportunities.flatMap(o=>o.themes))].sort();return head("Radar","Oportunidades","Filtre por elegibilidade, ação, pauta, tema e tipo. Aderência, elegibilidade e prontidão são dimensões independentes.")+'<div class="exports"><button class="btn" onclick="exportCSV()">Exportar CSV</button><button class="btn" onclick="exportJSON()">Exportar JSON</button><button class="btn" onclick="exportICS()">Exportar prazos .ICS</button></div><div class="toolbar"><input id="q" placeholder="Buscar título, organização, tema ou pauta"><select id="type"><option value="">Todos os tipos</option>'+[...new Set(D.opportunities.map(o=>o.type))].sort().map(x=>"<option>"+x+"</option>").join("")+'</select><select id="elig"><option value="">Elegibilidade</option><option>elegível</option><option>verificar</option><option>parcial</option></select><select id="personal"><option value="">Estado pessoal</option><option value="decidir">Para decidir</option><option value="vou_fazer">Vou fazer</option><option value="em_andamento">Em andamento</option><option value="pausado">Pausado</option><option value="concluido">Concluído</option><option value="sem_interesse">Não agora</option></select><select id="act"><option value="">Recomendação do Radar</option>'+[...new Set(D.opportunities.map(action))].sort().map(x=>"<option>"+x+"</option>").join("")+'</select><select id="theme"><option value="">Tema</option>'+themes.map(x=>"<option>"+x+"</option>").join("")+'</select><select id="sort"><option value="deadline">Prazo</option><option value="fit">Aderência</option><option value="fresh">Verificação</option></select></div><div id="olist" class="list"></div>'}
function stories(full=true){let cards='<div class="grid">'+D.stories.map(s=>'<article class="card" onclick="location.hash=\'pauta/'+s.id+'\'"><div class="eyebrow">'+s.status+'</div><h3>'+s.title+' '+stateMark("story",s.id)+'</h3><p>'+s.summary+'</p>'+s.themes.slice(0,5).map(x=>badge(x)).join("")+'</article>').join("")+'</div>';return full?head("Projetos","Pautas PLOT.","Investigações, propostas e experimentos editoriais relacionados às oportunidades e bases do Radar.")+ '<div class="exports"><a class="btn" href="#matriz">Abrir matriz pauta × oportunidade</a></div>'+cards:cards}
function dataQuestion(d){let n=(d.name+" "+d.themes.join(" ")).toLowerCase();if(n.includes("mortal")||n.includes("ouvidor"))return"Ajuda a dimensionar ocorrência, distribuição e padrões territoriais/temporais relevantes à pauta.";if(n.includes("cnes")||n.includes("estabelecimento"))return"Ajuda a localizar serviços, estabelecimentos e capacidade instalada no território.";if(n.includes("sisagua")||n.includes("captação"))return"Ajuda a mapear captação e contexto hídrico associado à infraestrutura.";if(n.includes("energia")||n.includes("aneel")||n.includes("dec")||n.includes("fec"))return"Ajuda a testar padrões de infraestrutura, continuidade e ocorrências elétricas sem presumir causalidade.";if(n.includes("educa")||n.includes("sidra"))return"Ajuda a cruzar território, características educacionais e desigualdades.";return"Base de apoio para cruzamentos, contextualização e teste de hipóteses."}
function datasetMeta(d){return{period:d.period||null,granularity:d.granularity||null,geoUnit:d.geoUnit||null,api:d.api??(/api/i.test(d.format||"")?"indicada":"não informada"),docs:d.docs||null,limitations:d.limitations||null,lastChecked:d.lastChecked||null}}
function datasetCompleteness(d){let m=datasetMeta(d),byKind={dataset:[d.coverage,d.frequency,d.format,d.url,m.period,m.granularity,m.geoUnit,m.docs,m.lastChecked],system:[d.coverage,d.frequency,d.format,d.url,m.docs,m.lastChecked],portal:[d.coverage,d.format,d.url,m.docs,m.lastChecked,m.limitations],catalog:[d.coverage,d.format,d.url,m.docs,m.lastChecked,m.limitations],"curated-source":[d.coverage,d.frequency,d.format,d.url,m.docs,m.lastChecked,m.limitations]},fields=byKind[d.kind]||byKind.dataset;return Math.round(fields.filter(Boolean).length/fields.length*100)}
function datasetKind(d){return({dataset:"Conjunto de dados",portal:"Portal de descoberta",catalog:"Catálogo de dados",system:"Sistema de dados","curated-source":"Fonte temática curada"}[d.kind]||"Conjunto de dados")}
function datasetPurposes(d){let s=[d.name,d.org,d.coverage,d.format,...(d.themes||[])].join(" ").toLowerCase(),p=[];const add=(x)=>{if(!p.includes(x))p.push(x)};if(/contrat|licita|pagamento|nfe|nota fiscal|convênio|compras|transparência|gastos/.test(s))add("Seguir dinheiro");if(/gis|cartograf|território|geograf|map|localidade|imóve|bairro|municip|geo/.test(s))add("Mapear território");if(/empresa|fornecedor|cnpj|negócio|estabelecimento/.test(s))add("Identificar empresas e atores");if(/saúde|mortal|nascid|sinasc|sih|cnes|obstetr|neonat|leito|profissionais/.test(s))add("Medir saúde e assistência");if(/água|hídr|outorga|captação|reservat/.test(s))add("Investigar água");if(/energia|aneel|ons|elétr|geração|transmiss/.test(s))add("Investigar energia");if(/diário oficial|processo|licenciamento|portaria|norma|ato público/.test(s))add("Reconstruir linha do tempo");if(/educa|escola|inep|censo escolar/.test(s))add("Investigar educação");if(!p.length)add("Contextualizar e cruzar dados");return p}
const STORY_DATA_STAGES={
 "data-centers":[["Empresas e atores","Identificar empresas e atores"],["Território","Mapear território"],["Energia","Investigar energia"],["Água","Investigar água"],["Licenciamento e atos","Reconstruir linha do tempo"],["Dinheiro público","Seguir dinheiro"]],
 "violencia-obstetrica":[["Rede e estabelecimentos","Medir saúde e assistência"],["Território","Mapear território"],["Ocorrências e assistência","Medir saúde e assistência"],["Atos e responsabilização","Reconstruir linha do tempo"],["Recursos públicos","Seguir dinheiro"]],
 "educacao":[["Escolas e educação","Investigar educação"],["Território","Mapear território"],["Recursos públicos","Seguir dinheiro"],["Atos e políticas","Reconstruir linha do tempo"]],
 "laudemio":[["Imóveis e território","Mapear território"],["Atores e titulares","Identificar empresas e atores"],["Transações e dinheiro","Seguir dinheiro"],["Atos e transformação temporal","Reconstruir linha do tempo"]]
};
function storyDataKit(s){let pool=D.datasets.filter(d=>(d.story||[]).includes(s.id)),stages=STORY_DATA_STAGES[s.id]||[["Contexto e cruzamentos","Contextualizar e cruzar dados"]],used=new Set(),rows=[];stages.forEach(([label,purpose])=>{let choices=pool.filter(d=>!used.has(d.id)&&datasetPurposes(d).includes(purpose)).sort((a,b)=>datasetCompleteness(b)-datasetCompleteness(a));let d=choices[0];if(d){used.add(d.id);rows.push({label,purpose,dataset:d})}else rows.push({label,purpose,dataset:null})});return rows}
function storyKitHTML(s){let rows=storyDataKit(s);return '<div class="investigationmap">'+rows.map((x,i)=>'<div class="investigationstage '+(x.dataset?"":"missing")+'"><div class="stageindex">'+String(i+1).padStart(2,"0")+'</div><div><div class="eyebrow">'+x.label+'</div>'+(x.dataset?'<h3><a href="#base/'+x.dataset.id+'">'+x.dataset.name+'</a> '+stateMark("dataset",x.dataset.id)+'</h3><div class="meta">'+x.dataset.org+' · '+datasetKind(x.dataset)+' · '+datasetCompleteness(x.dataset)+'% metadados</div>':'<h3>Lacuna de dados</h3><div class="meta">Nenhuma fonte vinculada cobre “'+x.purpose+'” nesta pauta.</div>')+'</div></div>').join("")+'</div>'}
function dataFiltersMeta(){return{themes:[...new Set(D.datasets.flatMap(d=>d.themes||[]))].sort(),coverage:[...new Set(D.datasets.map(d=>d.coverage).filter(Boolean))].sort(),kinds:[...new Set(D.datasets.map(d=>d.kind).filter(Boolean))].sort(),purposes:[...new Set(D.datasets.flatMap(datasetPurposes))].sort(),stories:D.stories.filter(s=>D.datasets.some(d=>(d.story||[]).includes(s.id)))}}
function dataToolbar(){let m=dataFiltersMeta();return '<div class="toolbar datatoolbar"><input id="dq" placeholder="Buscar base, órgão, tema ou território"><select id="dpersonal"><option value="">Uso pessoal</option><option value="vou_fazer">Salvas</option><option value="em_andamento">Em uso</option><option value="concluido">Já usei</option><option value="sem_interesse">Ocultas</option></select><select id="dkind"><option value="">Todos os tipos</option>'+m.kinds.map(x=>'<option value="'+x+'">'+datasetKind({kind:x})+'</option>').join("")+'</select><select id="dtheme"><option value="">Todos os temas</option>'+m.themes.map(x=>"<option>"+x+"</option>").join("")+'</select><select id="dpurpose"><option value="">Todas as finalidades</option>'+m.purposes.map(x=>"<option>"+x+"</option>").join("")+'</select><select id="dstory"><option value="">Todas as pautas</option>'+m.stories.map(s=>'<option value="'+s.id+'">'+s.title+'</option>').join("")+'</select><select id="dcoverage"><option value="">Todos os territórios</option>'+m.coverage.map(x=>"<option>"+x+"</option>").join("")+'</select><select id="dsort"><option value="relevance">Relevância</option><option value="name">Nome</option><option value="complete">Completude</option></select></div><div id="dcount" class="meta dataresultcount"></div>'}
function datasetRows(items){return '<div class="list">'+items.map(d=>'<div class="row"><div><div class="org">'+d.org+'</div><h3><a href="#base/'+d.id+'">'+d.name+'</a> '+stateMark("dataset",d.id)+'</h3><span class="meta">'+datasetKind(d)+'</span><div class="purposechips">'+datasetPurposes(d).map(x=>'<span class="purpose">'+x+'</span>').join("")+'</div>'+d.themes.map(x=>badge(x)).join("")+'</div><div>'+d.coverage+'<div class="meta">Atualização: '+d.frequency+'</div></div><div>'+d.format+'<div class="meta">'+(d.story?.length?"Ligada a "+d.story.map(x=>story(x)?.title||x).join(", "):"Sem pauta vinculada")+'</div></div><div><a class="btn" target="_blank" rel="noopener" href="'+d.url+'">Abrir base ↗</a></div></div>').join("")+'</div>'}
function datasets(full=true,items=D.datasets){let portals=items.filter(d=>["portal","catalog"].includes(d.kind)).length,avg=items.length?Math.round(items.reduce((n,d)=>n+datasetCompleteness(d),0)/items.length):0,needs=items.filter(d=>datasetCompleteness(d)<70).length;if(!full)return datasetRows(items);return head("Inteligência de dados","Dados & Bases","Encontre fontes por território, tema, pauta e tipo. O catálogo distingue bases analíticas, sistemas, portais de descoberta e fontes curadas.")+'<div class="metrics datametrics"><div class="metric"><b>'+items.length+'</b><span>registros de dados</span></div><div class="metric"><b>'+avg+'%</b><span>completude média</span></div><div class="metric"><b>'+needs+'</b><span>pedem auditoria</span></div><div class="metric"><b>'+portals+'</b><span>portais/catálogos</span></div></div>'+dataToolbar()+'<div id="dlist">'+datasetRows(items)+'</div>'}
function dataFilters(){let q=document.querySelector("#dq"),ps=document.querySelector("#dpersonal"),k=document.querySelector("#dkind"),th=document.querySelector("#dtheme"),pu=document.querySelector("#dpurpose"),st=document.querySelector("#dstory"),co=document.querySelector("#dcoverage"),so=document.querySelector("#dsort"),list=document.querySelector("#dlist"),count=document.querySelector("#dcount");if(!q)return;function go(){let needle=q.value.trim().toLowerCase(),a=D.datasets.filter(d=>(ps.value?editorialState("dataset",d.id)?.state===ps.value:editorialState("dataset",d.id)?.state!=="sem_interesse")&&[d.name,d.org,d.coverage,d.format,...(d.themes||[]),...(d.story||[]).map(x=>story(x)?.title||x)].join(" ").toLowerCase().includes(needle)&&(!k.value||d.kind===k.value)&&(!th.value||(d.themes||[]).includes(th.value))&&(!pu.value||datasetPurposes(d).includes(pu.value))&&(!st.value||(d.story||[]).includes(st.value))&&(!co.value||d.coverage===co.value));a.sort(so.value==="name"?(a,b)=>a.name.localeCompare(b.name,"pt-BR"):so.value==="complete"?(a,b)=>datasetCompleteness(b)-datasetCompleteness(a):((a,b)=>{let ap=(a.story||[]).length,bp=(b.story||[]).length;return bp-ap||datasetCompleteness(b)-datasetCompleteness(a)||a.name.localeCompare(b.name,"pt-BR")}));list.innerHTML=a.length?datasetRows(a):'<div class="warning">Nenhuma base corresponde aos filtros selecionados.</div>';count.textContent=a.length+' de '+D.datasets.length+' registros';}[q,ps,k,th,pu,st,co,so].forEach(x=>x.addEventListener("input",go));go()}
function datasetDetail(id){let d=D.datasets.find(x=>x.id===id);if(!d)return datasets();let m=datasetMeta(d);return'<button class="back" onclick="history.back()">← voltar</button>'+head(d.org,d.name,dataQuestion(d))+stateMark("dataset",d.id)+stateControl("dataset",d.id)+'<div class="detail">'+(d.kind?'<div class="kv"><b>Tipo de registro</b><div>'+datasetKind(d)+'</div></div>':"")+'<div class="kv"><b>Cobertura</b><div>'+d.coverage+'</div></div><div class="kv"><b>Frequência</b><div>'+d.frequency+'</div></div><div class="kv"><b>Formato</b><div>'+d.format+'</div></div><div class="kv"><b>Período disponível</b><div>'+(m.period||"a verificar")+'</div></div><div class="kv"><b>Granularidade</b><div>'+(m.granularity||"a verificar")+'</div></div><div class="kv"><b>Unidade geográfica</b><div>'+(m.geoUnit||"a verificar")+'</div></div><div class="kv"><b>API</b><div>'+m.api+'</div></div><div class="kv"><b>Documentação</b><div>'+(m.docs||"a verificar")+'</div></div><div class="kv"><b>Limitações conhecidas</b><div>'+(m.limitations||"a verificar")+'</div></div><div class="kv"><b>Completude do registro</b><div><div class="meter"><span style="width:'+datasetCompleteness(d)+'%"></span></div>'+datasetCompleteness(d)+'%</div></div><div class="kv"><b>Pautas</b><div>'+(d.story?.length?d.story.map(x=>'<a href="#pauta/'+x+'">'+(story(x)?.title||x)+'</a>').join("<br>"):"Nenhuma")+'</div></div><p><a class="btn primary" target="_blank" rel="noopener" href="'+d.url+'">Abrir fonte oficial ↗</a></p></div>'}
function themePage(id){let name=decodeURIComponent(id),same=x=>(x.themes||[]).some(t=>t.toLowerCase()===name.toLowerCase()),os=D.opportunities.filter(o=>same(o)&&editorialState("opportunity",o.id)?.state!=="sem_interesse"),ss=D.stories.filter(same),ds=D.datasets.filter(same);return'<button class="back" onclick="history.back()">← voltar</button>'+head("Tema",name,"Oportunidades, pautas e bases relacionadas.")+'<h2>Oportunidades</h2><div class="list">'+(os.map(orow).join("")||'<p class="meta">Nenhuma.</p>')+'</div><h2>Pautas</h2><div class="grid">'+ss.map(s=>'<article class="card" onclick="location.hash=\'pauta/'+s.id+'\'"><h3>'+s.title+'</h3><p>'+s.summary+'</p></article>').join("")+'</div><h2>Bases</h2>'+datasets(false,ds)}
function pipeline(){let active=D.opportunities.filter(o=>!["encerrada","descartada"].includes(o.status)&&o.eligibility!=="inelegível"),stages=[["decidir","Para decidir",o=>!editorialState("opportunity",o.id)],["vou_fazer","Vou fazer",o=>editorialState("opportunity",o.id)?.state==="vou_fazer"],["em_andamento","Em andamento",o=>editorialState("opportunity",o.id)?.state==="em_andamento"],["pausado","Pausado",o=>editorialState("opportunity",o.id)?.state==="pausado"],["concluido","Concluído",o=>editorialState("opportunity",o.id)?.state==="concluido"]];return head("Gestão pessoal","Pipeline","Seu fluxo de decisão e execução. Recomendações automáticas do Radar continuam nas fichas, sem competir com suas decisões.")+'<div class="kanban personalpipeline">'+stages.map(([key,label,test])=>{let rows=active.filter(test);return'<section class="lane '+key+'"><div class="eyebrow">'+label+'</div><b>'+rows.length+'</b>'+rows.map(o=>'<a class="mini" href="#oportunidade/'+o.id+'">'+o.title+' '+stateMark("opportunity",o.id)+'<small>'+o.org+(o.deadline?' · '+fmt(o.deadline):"")+'</small></a>').join("")+'</section>'}).join("")+'</div>'}
function matrix(){let active=D.opportunities.filter(o=>!["encerrada","descartada"].includes(o.status)&&o.eligibility!=="inelegível"&&o.story?.length&&editorialState("opportunity",o.id)?.state!=="sem_interesse");return head("Compatibilidade","Matriz pauta × oportunidade","Visão analítica secundária dos vínculos já cadastrados. A relação também aparece diretamente em cada pauta e oportunidade.")+'<div class="tablewrap"><table><thead><tr><th>Pauta</th>'+active.map(o=>'<th><a href="#oportunidade/'+o.id+'">'+o.title+'</a> '+stateMark("opportunity",o.id)+'</th>').join("")+'</tr></thead><tbody>'+D.stories.map(s=>'<tr><th><a href="#pauta/'+s.id+'">'+s.title+'</a></th>'+active.map(o=>'<td>'+(o.story.includes(s.id)?'<span class="matrixyes">'+(o.fit>=9?"forte":"possível")+'</span>':'—')+'</td>').join("")+'</tr>').join("")+'</tbody></table></div><div class="warning"><b>Regra editorial:</b> compatibilidade nunca substitui a maturidade da investigação nem justifica remodelar artificialmente uma pauta.</div>'}
function calendar(){let all=route().split("/")[1]==="todos",states=["vou_fazer","em_andamento"],a=D.opportunities.filter(o=>o.deadline&&!["encerrada","descartada"].includes(o.status)&&(all||states.includes(editorialState("opportunity",o.id)?.state))).sort((a,b)=>a.deadline.localeCompare(b.deadline));return head("Prazos","Calendário",all?"Todos os prazos ativos do Radar.":"Seus prazos: apenas oportunidades que você marcou como Vou fazer ou Em andamento.")+'<div class="viewtoggle"><a class="btn '+(!all?"primary":"")+'" href="#calendario">Meu calendário</a><a class="btn '+(all?"primary":"")+'" href="#calendario/todos">Todos os prazos</a></div>'+(a.length?'<div class="timeline">'+a.map(o=>'<div class="event"><div class="eyebrow">'+o.deadlineStatus+'</div><h3><a href="#oportunidade/'+o.id+'">'+o.title+'</a> '+stateMark("opportunity",o.id)+'</h3><b>'+fmt(o.deadline)+'</b> · '+o.org+'<div class="meta">'+nextStep(o)+'</div></div>').join("")+'</div>':'<div class="warning ok"><b>Nenhum prazo pessoal.</b> Marque uma oportunidade como “Vou fazer” ou “Em andamento” para ela aparecer aqui.</div>')}
function changes(embedded=false){let checks=D.opportunities.flatMap(o=>(o.verificationHistory||[]).map(h=>({date:h.date,title:o.title,detail:h.status,href:"#oportunidade/"+o.id,type:"verificação"}))),product=(D.changelog||[]).map(x=>({date:x.date,title:x.title,detail:x.detail,href:null,type:x.type})),rows=[...product,...checks].sort((a,b)=>b.date.localeCompare(a.date));return (embedded?"":head("Rastreabilidade","Mudanças","Histórico persistente de alterações do Radar e verificações das oportunidades."))+'<div class="timeline">'+rows.map(x=>'<div class="event"><div class="eyebrow">'+x.type+'</div><b>'+fmt(x.date)+'</b> · '+(x.href?'<a href="'+x.href+'">'+x.title+'</a>':x.title)+'<div class="meta">'+x.detail+'</div></div>').join("")+'</div>'}
function archive(){let tab=route().split("/")[1]||"factual",tests={factual:o=>["encerrada","descartada"].includes(o.status)||o.eligibility==="inelegível",sem_interesse:o=>editorialState("opportunity",o.id)?.state==="sem_interesse",concluidas:o=>editorialState("opportunity",o.id)?.state==="concluido"},a=D.opportunities.filter(tests[tab]||tests.factual);return head("Memória","Arquivo","Histórico factual e editorial sem poluir suas filas de trabalho.")+'<div class="viewtoggle"><a class="btn '+(tab==="factual"?"primary":"")+'" href="#arquivo">Encerradas / inelegíveis</a><a class="btn '+(tab==="sem_interesse"?"primary":"")+'" href="#arquivo/sem_interesse">Sem interesse</a><a class="btn '+(tab==="concluidas"?"primary":"")+'" href="#arquivo/concluidas">Concluídas</a></div><div class="list">'+(a.map(orow).join("")||'<p class="meta">Nenhum registro nesta categoria.</p>')+'</div>'}
function sourceStats(name){let needle=name.toLowerCase().split(" / ")[0],hits=D.opportunities.filter(o=>o.org.toLowerCase().includes(needle)||needle.includes(o.org.toLowerCase().split(" / ")[0]));let last=hits.map(o=>o.verified).filter(Boolean).sort().reverse()[0];return{hits:hits.length,last}}
function sourceDue(s){if(!s.lastChecked)return true;let limit={diária:1,semanal:7,quinzenal:15,mensal:30}[s.cadence]||15;return Math.max(0,-days(s.lastChecked))>=limit}
function sourceUrgency(s){let overdue=s.lastChecked?Math.max(0,-days(s.lastChecked)):999,limit={diária:1,semanal:7,quinzenal:15,mensal:30}[s.cadence]||15,weight={Alta:3,"Média":2,Monitorar:1}[s.priority]||1;return (overdue/limit)*10+weight}
function sourceQueue(){return D.sources.filter(sourceDue).sort((a,b)=>sourceUrgency(b)-sourceUrgency(a)||a.name.localeCompare(b.name))}
function methodNav(active="fontes"){return'<div class="exports"><a class="btn '+(active==="fontes"?"primary":"")+'" href="#metodologia">Fontes & método</a><a class="btn '+(active==="ia"?"primary":"")+'" href="#metodologia/ia">IA</a><a class="btn '+(active==="qualidade"?"primary":"")+'" href="#metodologia/qualidade">Qualidade</a><a class="btn '+(active==="mudancas"?"primary":"")+'" href="#metodologia/mudancas">Mudanças técnicas</a></div>'}
function aiMethod(){return head("Metodologia","Uso de IA","Como automação e modelos de IA entram no Radar — e quais decisões continuam dependendo de verificação editorial.")+methodNav("ia")+'<div class="detail"><div class="kv"><b>Descoberta e triagem</b><div>IA pode auxiliar a localizar, resumir, classificar e deduplicar oportunidades, fontes e bases.</div></div><div class="kv"><b>Verificação</b><div>Informação operacional — prazo, elegibilidade, valor, regras e acesso — deve ser conferida na fonte oficial antes de orientar uma decisão.</div></div><div class="kv"><b>Inferência</b><div>Campos desconhecidos permanecem pendentes. O Radar não deve preencher lacunas factuais por inferência do modelo.</div></div><div class="kv"><b>Decisão editorial</b><div>Aderência e relações entre pauta e oportunidade servem à organização; não substituem julgamento editorial nem justificam adaptar artificialmente uma investigação.</div></div><div class="kv"><b>Rastreabilidade</b><div>Alterações estruturais, auditorias e verificações ficam registradas nas áreas internas de Metodologia, sem ocupar a Visão Geral.</div></div></div>'}
function methods(section="fontes"){if(section==="ia")return aiMethod();if(section==="qualidade")return head("Metodologia","Qualidade","Validação estrutural e pendências internas do Radar.")+methodNav("qualidade")+quality(true);if(section==="mudancas")return head("Metodologia","Mudanças técnicas","Histórico de alterações internas, auditorias e verificações.")+methodNav("mudancas")+changes(true);let stats=D.sources.map(s=>({s,stat:sourceStats(s.name)})),high=stats.filter(x=>x.s.priority==="Alta").length,productive=stats.filter(x=>x.stat.hits>0).length,queue=sourceQueue();return head("Metodologia","Fontes & método","Descoberta não equivale a confirmação. O Radar combina web aberta, fontes oficiais, fontes especializadas e Gmail.")+methodNav("fontes")+'<h2>Fluxo editorial</h2><p class="lede">Descoberta → fonte oficial → elegibilidade → deduplicação → classificação → ação → histórico.</p><div class="warning"><b>Aderência ≠ elegibilidade ≠ prontidão.</b> A fonte oficial prevalece; newsletters servem como descoberta.</div><h2>Cobertura das fontes</h2><div class="metrics"><div class="metric"><b>'+D.sources.length+'</b><span>fontes monitoradas</span></div><div class="metric"><b>'+high+'</b><span>alta prioridade</span></div><div class="metric"><b>'+productive+'</b><span>com oportunidade associada</span></div><div class="metric"><b>'+queue.length+'</b><span>checagem vencida</span></div></div><h2>Fila de monitoramento</h2>'+(queue.length?'<div class="list">'+queue.slice(0,12).map(s=>'<div class="row"><div><h3>'+s.name+'</h3><span class="meta">'+s.category+'</span></div><div>'+s.priority+' prioridade</div><div>'+s.cadence+'<div class="meta">última checagem '+(s.lastChecked?fmt(s.lastChecked):"não registrada")+'</div></div><div>'+(s.url?'<a class="btn" target="_blank" rel="noopener" href="'+s.url+'">Checar fonte ↗</a>':'<span class="meta">Checar via Gmail</span>')+'</div></div>').join("")+'</div>':'<div class="warning ok"><b>Monitoramento em dia:</b> nenhuma fonte ultrapassou sua cadência.</div>')+'<h2>Fontes monitoradas</h2><div class="list">'+stats.map(x=>{let s=x.s,z=x.stat;return'<div class="row"><div><h3>'+s.name+'</h3><span class="meta">'+s.type+'</span></div><div>'+s.scope+'<div class="meta">'+s.category+' · '+z.hits+' oportunidade(s)</div></div><div>'+s.priority+' prioridade<div class="meta">monitoramento '+s.cadence+' · fonte checada '+(s.lastChecked?fmt(s.lastChecked):"nunca")+(sourceDue(s)?' · revisar':' · em dia')+'</div></div><div>'+(s.url?'<a class="btn" target="_blank" rel="noopener" href="'+s.url+'">Fonte ↗</a>':'<span class="meta">Gmail / descoberta</span>')+'</div></div>'}).join("")+'</div>'}
function odetail(id){let o=opp(id);if(!o)return home();let hist=o.verificationHistory||[];return'<button class="back" onclick="history.back()">← voltar</button><div class="detail"><div class="eyebrow">'+o.org+'</div><h1 class="detailtitle">'+o.title+'</h1>'+stateMark("opportunity",o.id)+stateControl("opportunity",o.id)+'<p class="lede">'+o.desc+'</p><div class="kv"><b>Status</b><div>'+badge(o.status,false)+' '+badge(o.deadlineStatus,false)+'</div></div><div class="kv"><b>Prontidão</b><div>'+badge(readiness(o),false)+'</div></div><div class="kv"><b>Prazo</b><div>'+(o.deadline?fmt(o.deadline):"Não confirmado / contínuo")+'</div></div><div class="kv"><b>Elegibilidade</b><div>'+badge(o.eligibility,false)+'</div></div><div class="kv"><b>Aderência PLOT.</b><div><span class="score">'+o.fit+'/10</span></div></div><div class="kv"><b>Temas</b><div>'+o.themes.map(x=>badge(x)).join("")+'</div></div>'+(o.value?'<div class="kv"><b>Valor</b><div>'+o.value+'</div></div>':"")+(o.duration?'<div class="kv"><b>Duração</b><div>'+o.duration+'</div></div>':"")+(o.modality?'<div class="kv"><b>Modalidade</b><div>'+o.modality+'</div></div>':"")+(o.opens?'<div class="kv"><b>Abertura</b><div>'+fmt(o.opens)+'</div></div>':"")+(o.documents?.length?'<div class="kv"><b>Documentos</b><div>'+o.documents.join("<br>")+'</div></div>':"")+(o.restrictions?.length?'<div class="kv"><b>Restrições</b><div>'+o.restrictions.join("<br>")+'</div></div>':"")+'<div class="kv"><b>Pautas relacionadas</b><div>'+(o.story.length?o.story.map(x=>'<a href="#pauta/'+x+'">'+story(x).title+'</a>').join("<br>"):"Nenhuma")+'</div></div><div class="kv"><b>Última verificação</b><div>'+fmt(o.verified)+' · '+freshness(o)+'</div></div>'+(hist.length?'<div class="kv"><b>Histórico</b><div>'+hist.map(h=>fmt(h.date)+' · '+h.status).join("<br>")+'</div></div>':"")+'<p><a class="btn primary" target="_blank" rel="noopener" href="'+o.rules+'">Fonte oficial ↗</a>'+(o.apply?'<a class="btn" target="_blank" rel="noopener" href="'+o.apply+'">Inscrição ↗</a>':"")+'</p></div>'}
function sdetail(id){let s=story(id);if(!s)return stories();let os=D.opportunities.filter(o=>o.story.includes(id)&&o.status!=="encerrada"&&editorialState("opportunity",o.id)?.state!=="sem_interesse"),ds=D.datasets.filter(d=>d.story.includes(id));return'<button class="back" onclick="history.back()">← voltar</button><div class="detail"><div class="eyebrow">'+s.status+'</div><h1 class="detailtitle">'+s.title+'</h1>'+stateMark("story",s.id)+stateControl("story",s.id)+'<p class="lede">'+s.summary+'</p></div>'+submissionHistory(s.id)+'<h2>Mapa de investigação</h2><p class="meta">Cobertura operacional das etapas da pauta com as bases já cadastradas. Lacunas aparecem explicitamente e não são preenchidas por inferência.</p>'+storyKitHTML(s)+'<h2>Oportunidades relacionadas</h2>'+(os.length?'<div class="list">'+os.map(orow).join("")+'</div>':'<p class="meta">Nenhuma compatibilidade ativa.</p>')+'<div class="warning"><b>Regra editorial:</b> não adaptar artificialmente a pauta ao edital.</div><h2>Todas as bases relacionadas</h2>'+(ds.length?datasets(false,ds):'<p class="meta">Nenhuma base vinculada.</p>')}
function filters(){let q=document.querySelector("#q"),t=document.querySelector("#type"),e=document.querySelector("#elig"),pe=document.querySelector("#personal"),ac=document.querySelector("#act"),th=document.querySelector("#theme"),s=document.querySelector("#sort"),list=document.querySelector("#olist"),preset=route().split("/")[1]||"",labels={decidir:"Para decidir",preparar:"Em preparação",andamento:"Em andamento",prazo30:"Encerram em 30 dias",rolling:"Fluxo contínuo",acionaveis:"Acionáveis"};function presetOk(o){let st=editorialState("opportunity",o.id)?.state;if(preset==="decidir")return !st;if(preset==="preparar")return st==="vou_fazer";if(preset==="andamento")return st==="em_andamento";if(preset==="prazo30")return o.deadline&&days(o.deadline)>=0&&days(o.deadline)<=30;if(preset==="rolling")return o.deadlineStatus==="rolling";if(preset==="acionaveis")return ["preparar","avaliar/aplicar"].includes(action(o));return st!=="sem_interesse"}function personalOk(o){let st=editorialState("opportunity",o.id)?.state||"";return !pe.value||(pe.value==="decidir"?!st:st===pe.value)}function go(){let a=D.opportunities.filter(o=>presetOk(o)&&!["encerrada","descartada"].includes(o.status)&&[o.title,o.org,...o.themes,...o.story.map(x=>story(x)?.title||"")].join(" ").toLowerCase().includes(q.value.toLowerCase())&&(!t.value||o.type===t.value)&&(!e.value||o.eligibility===e.value)&&personalOk(o)&&(!ac.value||action(o)===ac.value)&&(!th.value||o.themes.includes(th.value)));a.sort(s.value==="fit"?(a,b)=>b.fit-a.fit:s.value==="fresh"?(a,b)=>(b.verified||"").localeCompare(a.verified||""):(a,b)=>(a.deadline||"9999").localeCompare(b.deadline||"9999"));list.innerHTML=(preset&&labels[preset]?'<div class="activepreset">Filtro ativo: <b>'+labels[preset]+'</b> <a href="#oportunidades">limpar ×</a></div>':"")+(a.map(orow).join("")||"<p>Nenhum resultado.</p>")}[q,t,e,pe,ac,th,s].forEach(x=>x.addEventListener("input",go));go()}

function validateRadar(){
 let errors=[],warnings=[],ids=new Set(),storyIds=new Set(D.stories.map(s=>s.id)),dateRx=/^\d{4}-\d{2}-\d{2}$/;
 const add=(level,kind,id,msg)=>(level==="error"?errors:warnings).push({kind,id,msg});
 D.opportunities.forEach(o=>{
  if(!o.id)add("error","oportunidade","sem-id","ID ausente"); else if(ids.has(o.id))add("error","oportunidade",o.id,"ID duplicado"); else ids.add(o.id);
  ["title","org","type","scope","status","eligibility"].forEach(k=>{if(!o[k])add("error","oportunidade",o.id,k+" ausente")});
  if(typeof o.fit!=="number"||o.fit<0||o.fit>10)add("error","oportunidade",o.id,"aderência fora de 0–10");
  if(!o.rules||!/^https?:\/\//.test(o.rules))add("error","oportunidade",o.id,"fonte oficial ausente/inválida");
  ["deadline","opens","verified"].forEach(k=>{if(o[k]&&!dateRx.test(o[k]))add("error","oportunidade",o.id,k+" em formato inválido")});
  (o.story||[]).forEach(x=>{if(!storyIds.has(x))add("error","oportunidade",o.id,"pauta inexistente: "+x)});
  if(!o.summary)add("warning","oportunidade",o.id,"resumo editorial próprio ainda não cadastrado");
  if(!o.verified)add("warning","oportunidade",o.id,"sem data de verificação");
 });
 let snames=new Set();
 D.sources.forEach(s=>{
  if(!s.name)add("error","fonte","sem-nome","nome ausente"); else if(snames.has(s.name))add("error","fonte",s.name,"nome duplicado"); else snames.add(s.name);
  ["type","scope","priority","cadence","category","lastChecked"].forEach(k=>{if(!s[k])add("error","fonte",s.name,k+" ausente")});
  if(s.url&&!/^https?:\/\//.test(s.url))add("error","fonte",s.name,"URL inválida");
  if(!["diária","semanal","quinzenal","mensal"].includes(s.cadence))add("error","fonte",s.name,"cadência inválida");
  if(s.lastChecked&&!dateRx.test(s.lastChecked))add("error","fonte",s.name,"lastChecked em formato inválido");
 });
 let dids=new Set();
 D.datasets.forEach(d=>{
  if(!d.id)add("error","base","sem-id","ID ausente"); else if(dids.has(d.id))add("error","base",d.id,"ID duplicado"); else dids.add(d.id);
  let kinds=["dataset","portal","catalog","system","curated-source"];
  if(!d.kind||!kinds.includes(d.kind))add("error","base",d.id,"tipo inválido ou ausente");
  if(!d.url||!/^https?:\/\//.test(d.url))add("error","base",d.id,"URL ausente/inválida");
  (d.story||[]).forEach(x=>{if(!storyIds.has(x))add("error","base",d.id,"pauta inexistente: "+x)});
  let m=datasetMeta(d),required=d.kind==="dataset"?["period","granularity","geoUnit","docs","lastChecked"]:d.kind==="system"?["docs","lastChecked"]:["docs","limitations","lastChecked"];required.forEach(k=>{if(!m[k])add("warning","base",d.id,k+" pendente")});
 });
 return{errors,warnings,checked:D.opportunities.length+D.datasets.length+D.stories.length+D.sources.length};
}
function quality(embedded=false){
 let q=validateRadar(),groups=[...q.errors.map(x=>({...x,level:"erro"})),...q.warnings.map(x=>({...x,level:"pendência"}))];
 return (embedded?"":head("Controle de qualidade","Validação do Radar","Checagem automática de integridade estrutural. Erros indicam quebra objetiva do schema; pendências indicam metadados que ainda precisam de confirmação editorial."))+
 '<div class="metrics qualitymetrics"><div class="metric"><b>'+q.checked+'</b><span>registros checados</span></div><div class="metric"><b>'+q.errors.length+'</b><span>erros estruturais</span></div><div class="metric"><b>'+q.warnings.length+'</b><span>pendências</span></div><div class="metric"><b>'+D.opportunities.filter(o=>o.summary).length+'</b><span>resumos próprios</span></div></div>'+
 (q.errors.length?'<div class="warning danger"><b>Atenção:</b> existem erros estruturais que devem ser corrigidos antes da próxima carga.</div>':'<div class="warning ok"><b>Estrutura válida:</b> nenhum erro crítico detectado.</div>')+
 '<div class="list qualitylist">'+groups.map(x=>'<div class="row"><div><span class="badge">'+x.level+'</span><h3>'+x.id+'</h3></div><div>'+x.kind+'</div><div>'+x.msg+'</div><div></div></div>').join("")+'</div>';
}

function closeNav(){document.querySelector("#nav")?.classList.remove("open")}function render(){closeNav();nav();renderAuth();let [base,id]=route().split("/");if(base==="oportunidade")app.innerHTML=odetail(id);else if(base==="base")app.innerHTML=datasetDetail(id);else if(base==="pauta")app.innerHTML=sdetail(id);else if(base==="tema")app.innerHTML=themePage(id);else if(base==="metodologia")app.innerHTML=methods(id||"fontes");else app.innerHTML=({visao:home,oportunidades:opportunities,pautas:stories,dados:datasets,pipeline,matrix:matrix,matriz:matrix,calendario:calendar,arquivo:archive}[base]||home)();if(base==="oportunidades")filters();if(base==="dados")dataFilters();window.scrollTo(0,0)}
window.addEventListener("hashchange",render);document.querySelector("#menu").onclick=()=>{let n=document.querySelector("#nav"),open=n.classList.toggle("open");document.querySelector("#menu").setAttribute("aria-expanded",String(open));document.querySelector("#menu").setAttribute("aria-label",open?"Fechar menu":"Abrir menu")};document.querySelector("#nav").addEventListener("click",e=>{if(e.target.closest("a"))closeNav()});render();
initEditorial();
