window.RADAR={
opportunities:[
{id:"dvs",title:"DVS Mentorship Program",org:"Data Visualization Society",type:"Mentoria",themes:["Dados","Visualização"],scope:"Internacional",deadline:null,deadlineStatus:"confirmar",eligibility:"verificar",fit:10,status:"aberta",story:[],rules:"https://datavisualizationsociety.org/mentorship/",apply:null,verified:"2026-09-23",desc:"Mentoria em visualização de dados. O fechamento da rodada atual deve ser reconfirmado antes da candidatura."},
{id:"wcsj",title:"WCSJ2027 Travel Fellowship",org:"World Conference of Science Journalists",type:"Fellowship",themes:["Ciência","Clima","Saúde"],scope:"Internacional",deadline:"2026-10-23",deadlineStatus:"confirmado",eligibility:"elegível",fit:9,status:"aberta",story:["data-centers","violencia-obstetrica"],rules:"https://registration.wcsj2027.org/wcsj27/fellowships",apply:"https://registration.wcsj2027.org/wcsj27/fellowships",verified:"2026-09-23",desc:"Apoio de viagem para a conferência mundial de jornalismo científico. Verificar novamente regras finais antes do envio."},
{id:"kw",title:"Knight-Wallace Fellowship 2027–28",org:"Wallace House / University of Michigan",type:"Fellowship",themes:["Investigação","Dados","Visual"],scope:"Internacional",deadline:"2026-12-01",deadlineStatus:"abertura_futura",eligibility:"elegível",fit:10,status:"preparar",story:[],rules:"https://wallacehouse.umich.edu/knight-wallace/how-to-apply/",apply:null,verified:"2026-09-23",desc:"Fellowship de longo prazo. A aplicação deve respeitar integralmente as regras da instituição, inclusive restrições de uso de IA."},
{id:"reuters",title:"Reuters Institute Journalist Fellowship",org:"Reuters Institute / University of Oxford",type:"Fellowship",themes:["Investigação","Formação"],scope:"Internacional",deadline:null,deadlineStatus:"abertura_futura",eligibility:"elegível",fit:9.5,status:"preparar",story:[],rules:"https://reutersinstitute.politics.ox.ac.uk/our-journalist-fellowship-programme",apply:null,verified:"2026-09-23",desc:"Próximo ciclo esperado para 2027; não apresentar como candidatura aberta até confirmação oficial."},
{id:"pulitzer-data",title:"Data Journalism Grants",org:"Pulitzer Center",type:"Grant",themes:["Dados","Investigação","Visualização"],scope:"Internacional",deadline:null,deadlineStatus:"rolling",eligibility:"verificar",fit:10,status:"aberta",story:["data-centers"],rules:"https://pulitzercenter.org/grants-fellowships/opportunities-journalists/data-journalism-grants",apply:null,verified:"2026-09-23",desc:"Financiamento para projetos de jornalismo de dados. Status e regras devem ser reconfirmados no momento da candidatura."},
{id:"dialogue",title:"Pitches — Dialogue Earth",org:"Dialogue Earth",type:"Pitch",themes:["Clima","Ambiente","Dados"],scope:"Internacional",deadline:null,deadlineStatus:"rolling",eligibility:"elegível",fit:9,status:"aberta",story:["data-centers"],rules:"https://dialogue.earth/",apply:null,verified:"2026-09-23",desc:"Canal permanente de pitches; útil para recortes ambientais e climáticos."},
{id:"row-labor",title:"Labor x Tech Reporting",org:"Rest of World",type:"Pitch",themes:["Tecnologia","Trabalho"],scope:"Internacional",deadline:null,deadlineStatus:"confirmar",eligibility:"verificar",fit:9,status:"aberta",story:["data-centers"],rules:"https://restofworld.org/rest-of-worlds-labor-x-tech-reporting/",apply:null,verified:"2026-09-23",desc:"Possível encaixe para recorte documentado sobre tecnologia e trabalho. Status atual precisa ser confirmado."}
],
stories:[
{id:"data-centers",title:"Data centers no semiárido baiano",status:"Apuração avançada",themes:["Clima","Energia","Água","IA/tech","Infraestrutura","Governança"],summary:"Investigação sobre expansão de data centers no semiárido baiano, infraestrutura, recursos e governança."},
{id:"violencia-obstetrica",title:"Violência obstétrica na Bahia",status:"Apuração",themes:["Saúde","Gênero","Direitos humanos","Transparência","Dados"],summary:"Investigação sobre violência obstétrica, mortalidade, responsabilização e desigualdade na Bahia."},
{id:"futebol",title:"Futebol feminino — Seleção",status:"Experimento em execução",themes:["Esporte","Gênero","Dados","Visualização"],summary:"Base e narrativa visual sobre origem territorial e trajetória de convocadas da Seleção."},
{id:"educacao",title:"Educação — CEP e oportunidades",status:"Proposta submetida",themes:["Educação","Desigualdade","Dados"],summary:"Projeto sobre desigualdade territorial e oportunidades educacionais."},
{id:"laudemio",title:"Laudêmio",status:"Exploração",themes:["Território","Propriedade","Transparência","História"],summary:"Investigação exploratória sobre enfiteuse, laudêmio e territórios em Salvador."},
{id:"evore",title:"Evore SAJ / médicos e processos",status:"Hipótese futura",themes:["Saúde","Justiça","Dados"],summary:"Hipótese de investigação. A existência de padrão de má conduta não está estabelecida e precisa ser testada documentalmente."}
],
datasets:[
{id:"aneel",name:"ANEEL Dados Abertos",org:"ANEEL",themes:["Energia","Infraestrutura"],coverage:"Brasil",frequency:"Variável por conjunto",format:"CSV/API",story:["data-centers"],url:"https://dadosabertos.aneel.gov.br/"},
{id:"ons",name:"ONS Dados Abertos",org:"ONS",themes:["Energia"],coverage:"Brasil",frequency:"Variável por conjunto",format:"CSV/API",story:["data-centers"],url:"https://dados.ons.org.br/"},
{id:"saude",name:"DATASUS / Ministério da Saúde",org:"Ministério da Saúde",themes:["Saúde"],coverage:"Brasil",frequency:"Variável",format:"CSV/Sistemas",story:["violencia-obstetrica"],url:"https://datasus.saude.gov.br/"},
{id:"sidra",name:"IBGE / SIDRA",org:"IBGE",themes:["Demografia","Economia"],coverage:"Brasil",frequency:"Variável",format:"API/Tabelas",story:["data-centers","educacao"],url:"https://sidra.ibge.gov.br/"},
{id:"dadosgov",name:"Portal Brasileiro de Dados Abertos",org:"Governo Federal",themes:["Dados públicos"],coverage:"Brasil",frequency:"Catálogo",format:"Múltiplos",story:[],url:"https://dados.gov.br/"},
{id:"transparencia",name:"Portal da Transparência",org:"CGU",themes:["Transparência","Gastos públicos"],coverage:"Brasil",frequency:"Variável",format:"Portal/API",story:["data-centers"],url:"https://portaldatransparencia.gov.br/"}
],
sources:[
["GIJN","Oportunidades / investigação","Global","Alta","https://gijn.org/topic/opportunities/"],["Knight Center","Formação / jornalismo","Américas","Alta","https://knightcenter.utexas.edu/"],["Escola de Dados / OKBR","Dados / formação","Brasil","Alta","https://escoladedados.org/"],["Abraji","Investigação / formação","Brasil","Alta","https://abraji.org.br/"],["ICIJ","Investigação","Global","Alta","https://www.icij.org/"],["OCCRP","Investigação","Global","Alta","https://www.occrp.org/"],["Fiquem Sabendo","Transparência / dados","Brasil","Alta","https://fiquemsabendo.com.br/"],["Datawrapper","Dataviz","Global","Média","https://www.datawrapper.de/"],["The Pudding","Visual / dados","Global","Alta","https://pudding.cool/"],["Tech Policy Press","Tecnologia / políticas públicas","Global","Alta","https://www.techpolicy.press/"],["Agência Tatu","Dados / Nordeste","Brasil","Alta","https://www.agenciatatu.com.br/"],["Gênero e Número","Gênero / dados","Brasil","Alta","https://www.generonumero.media/"]]
};